version: '3'
services:
  nginx:
    image: nginx:1.23
    container_name: web
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    links:
      - app

  app:
    build: ./php
    container_name: app
    links:
      - mysql
    volumes:
      - ./public:/var/www/html
      - ./php/xhprof:/var/www/html/xhprof

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./etc/my.cnf:/etc/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: